######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 20 15:57:51 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . sample
INCLUDEPATH += .

# Input
SOURCES += main.cpp
